version: "3.1"
services:
  app:
    build: .
    args:
        user: webadmin
        uid: 1000
    context: ./
    Dockerfile: Dockerfile
    redis:
        image: redis:latest
    container_name: yolo-app
    restart: unless-stopped
    volumes: 
     - ./:/var/www/html
    ports:
     - 8080:80
    networks:
     - mailer 
    depends_on:
    - db

db:
    image: alpine
    container_name: yolo-db
    restart: unless-stopped
    environment: 
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql 
     volumes: 
      - ./mysql:/var/lib
     ports:
      - 4306:4306
     networks:
      - mailer 

networks:
    mailer: 
        driver: bridge



  